spring:
  jpa:
    database: MYSQL
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        cache.use_query_cache: false
        generate_statistics: false
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/bonheure?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    name: bonheure
    username: root
    type: com.zaxxer.hikari.HikariDataSource
    password: root
  application:
    name: service-streamlink
    security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 3600000  # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds