spring:
  jpa:
    database: MYSQL
    show_sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false
        cache.use_query_cache: false
        generate_statistics: false
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/bonheure?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    name: bonheure
    username: root
    type: com.zaxxer.hikari.HikariDataSource
    password: root
  application:
    name: service-streamlink